---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ php82_packages }}"
    state: latest

- name: Add php8.2 repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP 8.2
  ansible.builtin.package:
    name: "{{ php82_php_packages }}"
    state: latest
