{
 "title": "EKS Control Plane",
 "description": "This dashboard graphs EKS Control Plane metrics as described in the EKS best practices guide: https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#monitor-control-plane-metrics. \r\n\r\nIt tracks API server activity, admission controller performance, client request latencies, and the etcd database size.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "EKS API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Latency to EKS API Server",
   "type": "timeseries",
   "description": "Monitor the latency of outbound requests from the API server to other services.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_request_duration_seconds_bucket{job=\"apiserver\", le=\"0.005\", verb=~\"GET|POST\"}[5m])) by (host, verb)",
     "legendFormat": "{{verb}} - {{host}}"
    }
   ]
  },
  {
   "title": "HTTP Request Volume to EKS API Server",
   "type": "bargauge",
   "description": "Track the total number of outbound HTTP requests made by the API server.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total[5m])) by (method, code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "EKS Admission Controller Latency",
   "type": "timeseries",
   "description": "Show the latency of different admission controllers. This is crucial for understanding the overhead added by admission controllers.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_admission_controller_admission_duration_seconds_count{job=\"apiserver\"}[5m])) by (name, operation)",
     "legendFormat": "{{name}} - {{ operation }}"
    }
   ]
  },
  {
   "title": "EKS API Server Total Requests",
   "type": "bargauge",
   "description": "Visualize the total number of API server requests.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb, code)",
     "legendFormat": "{{verb}} - {{code}}"
    }
   ]
  },
  {
   "title": "EKS ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "EKS Etcd Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le, operation, type))",
       "legendFormat": "{{operation}} - {{type}}"
      }
     ]
    },
    {
     "title": "EKS Etcd Database Size",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(apiserver_storage_size_bytes) by (cluster) / 1024^3"
      }
     ]
    }
   ]
  },
  {
   "title": "EKS Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "EKS Control Plane Version",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(kubernetes_build_info{job=\"kubelet\"}, \"minor\", \"$1\", \"minor\", \"(.+)[+]$\")",
       "legendFormat": "EKS Version: v{{major}}.{{minor}}"
      }
     ]
    },
    {
     "title": "EKS Data Plane Version",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_replace(kube_node_info, \"simple_version\", \"$1.$2\", \"kubelet_version\", \"^v([0-9]+)\\\\.([0-9]+).*\")",
       "legendFormat": "Node Version: v{{simple_version}}"
      }
     ]
    }
   ]
  }
 ]
}