{
 "title": "Karpenter",
 "description": "Display all useful Karpenter metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(label_karpenter_sh_provisioner_name)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "query_result(kube_deployment_created OR kube_statefulset_created)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "karpenter_provisioner_usage{provisioner=\"$provisioner\", resource_type=\"cpu\"}",
     "legendFormat": "Provisioner  Usage"
    },
    {
     "expr": "karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"cpu\"}",
     "legendFormat": "Provisioner Limits"
    }
   ]
  },
  {
   "title": "Provisioner CPU % Limits",
   "type": "stat",
   "description": "Specifies the percentage of resource limits that has been provisioned.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karpenter_provisioner_usage{provisioner=\"$provisioner\", resource_type=\"cpu\"} / karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % Allocated",
   "type": "stat",
   "description": "Specifies the percentage of allocatable resource that has been allocated.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "karpenter_provisioner_usage{provisioner=\"$provisioner\", resource_type=\"memory\"}",
     "legendFormat": "Provisioner  Usage"
    },
    {
     "expr": "karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"memory\"}",
     "legendFormat": "Provisioner Limits"
    }
   ]
  },
  {
   "title": "Provisioner Memory % Limits",
   "type": "stat",
   "description": "Specifies the percentage of resource limits that has been provisioned.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "karpenter_provisioner_usage{provisioner=\"$provisioner\", resource_type=\"memory\"} / karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory % Allocated",
   "type": "stat",
   "description": "Specifies the percentage of allocatable resource that has been allocated.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Node AZ Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod AZ Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total number of pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"cpu\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"cpu\"}",
       "legendFormat": "Allocatable Limits"
      }
     ]
    },
    {
     "title": "Cluster Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"})",
       "legendFormat": "Allocated"
      },
      {
       "expr": "sum(karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"memory\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "karpenter_provisioner_limit{provisioner=\"$provisioner\", resource_type=\"memory\"}",
       "legendFormat": "Allocatable Limits"
      }
     ]
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "idelta(karpenter_nodes_created_total{provisioner=\"$provisioner\"}[$__rate_interval])",
     "legendFormat": "created"
    },
    {
     "expr": "idelta(karpenter_nodes_terminated_total{provisioner=\"$provisioner\"}[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Node AZ Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "count(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"pods\"}) by (zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU % Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"cpu\"}) / karpenter_nodes_allocatable{provisioner_name=\"$provisioner\",resource_type=\"cpu\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Memory % Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(karpenter_nodes_total_pod_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"} + karpenter_nodes_total_daemon_requests{provisioner_name=\"$provisioner\",resource_type=\"memory\"}) / karpenter_nodes_allocatable{provisioner_name=\"$provisioner\", resource_type=\"memory\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "idelta(karpenter_interruption_received_messages_total[1m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Deleted Interruption Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(idelta(karpenter_interruption_deleted_messages_total[1m]))",
     "legendFormat": "Number of messages deleted"
    }
   ]
  },
  { "title": "Pods by Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\", name=~\"$application-[0-9]+.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod AZ Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{provisioner=\"$provisioner\",name=~\"$application-[0-9]+.*\"}) by (zone)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Skew ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "max(sum(karpenter_pods_state{provisioner=\"$provisioner\", name=~\"$application-[0-9]+.*\"}) by (zone)) - min(sum(karpenter_pods_state{provisioner=\"$provisioner\", name=~\"$application-[0-9]+.*\"}) by (zone))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}