{
 "title": "Application Deployments",
 "description": "Custom Monitoring for Deployments",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Project",
    "query": {
     "query": "label_values({namespace=\"default\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Horizontal AutoScaler",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~\"$Project-hpa\"}",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Containers CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\",container=~\"api|worker-.+\",pod=~\"^$Project-deployment.*$\"}[1m])) by (container, pod)",
     "legendFormat": "usage: {{ pod }} | {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"default\",resource=\"cpu\",container=~\"api|worker-.+\",pod=~\"$Project-deployment.*\"}",
     "legendFormat": "request: {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"default\",container=~\"api|worker-.+\",pod=~\"^$Project-deployment.*$\"}) by (pod,container)",
     "legendFormat": "usage: {{ pod }} | {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"default\",resource=\"memory\",container=~\"api|worker-.+\",pod=~\"$Project-deployment.*\"}",
     "legendFormat": "request: {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment network I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"default\",pod=~\"^$Project-deployment.*$\"}[1m])) by (pod)",
       "legendFormat": "-> {{ pod }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"default\",pod=~\"^$Project-deployment.*$\"}[1m])) by (pod)",
       "legendFormat": "<- {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}