{
 "title": "Kubernetes Workloads CPU and Memory Metrics",
 "description": "Simple dashboard for observing your Kubernetes Deployment CPU and Memory usage.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_condition,namespace)"
    }
   },
   {
    "name": "workload_type",
    "query": "deployment, statefulset, daemonset"
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$workload_type\"},workload)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Pods CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected workload",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$workload.*\",image!=\"\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n\n",
     "legendFormat": "$workload - limit"
    },
    {
     "expr": "sum(\n    (\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n\n",
     "legendFormat": "$workload  - request"
    },
    {
     "expr": "sum(\n    (\n        rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$workload.*\",image!=\"\",image!=\"\"}[$__rate_interval])\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n\n",
     "legendFormat": "$workload  - usage"
    }
   ]
  },
  {
   "title": "All Pods Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected workload",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    (\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)",
     "legendFormat": "$workload - limit"
    },
    {
     "expr": "sum(\n    (\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)",
     "legendFormat": "$workload  - request"
    },
    {
     "expr": "sum(\n    (\n        container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod.*\",image!=\"\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n",
     "legendFormat": "$workload  - usage"
    }
   ]
  },
  {
   "title": "CPU Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    (\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$workload.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Resource Usage - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Pods CPU usage for selected workload",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "avg(\n\t(\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=\"$pod\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)",
       "legendFormat": "$pod - limit"
      },
      {
       "expr": "avg(\n\t(\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=\"$pod\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)\n",
       "legendFormat": "$pod  - request"
      },
      {
       "expr": "avg(\n\t(\n        rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval])\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)\n",
       "legendFormat": "$pod  - usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Pods emory usage for selected workload",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n\t(\n        kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=\"$pod\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)",
       "legendFormat": "$pod - limit"
      },
      {
       "expr": "avg(\n\t(\n        kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=\"$pod\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)\n\n",
       "legendFormat": "$pod  - request"
      },
      {
       "expr": "avg(\n\t(\n        container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}\n    )\n    * on (pod) group_left()\n    (\n        namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$workload_type\"}\n    )\n) by (pod)\n",
       "legendFormat": "$pod  - usage"
      }
     ]
    }
   ]
  }
 ]
}