---
- name: Checking if composer exists
  ansible.builtin.stat:
    path: /usr/local/bin/composer
  register: composer_status

- name: Validate Composer checksum
  ansible.builtin.get_url:
    checksum: "sha384:e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02"
    dest: /tmp/
    url: https://getcomposer.org/installer
  when: composer_status.stat.exists==false

- name: Download and install Composer
  ansible.builtin.shell: "curl -sS https://getcomposer.org/installer | php"
  args:
    chdir: /tmp/
    creates: /usr/local/bin/composer
  when: composer_status.stat.exists==false

- name: Add Composer to global path
  ansible.builtin.copy:
    dest: /usr/local/bin/composer
    group: root
    mode: "0755"
    owner: root
    src: /tmp/installer
    remote_src: yes
  when: composer_status.stat.exists==false
