# AirGradient Pro v4.2 DIY edition

substitutions:
  id: "1"
  devicename: "airgradient-pro"
  upper_devicename: "AirGradient Pro"
  temperature_units: "C"

esphome:
  name: "${devicename}-${id}"
  friendly_name: "${upper_devicename} ${id}"

esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 10.0.0.2
    gateway: 10.0.0.1
    subnet: 255.255.255.0

  ap:
    ssid: "Airgradient Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxxxxxx"

captive_portal:

web_server:
  port: 80
  include_internal: true

switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"
    icon: "mdi:cellphone-arrow-down"

i2c:
  sda: D2
  scl: D1

font:
  - file: "gfonts://Open Sans"
    id: open_sans_14
    size: 14
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_9
    size: 9
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_20
    size: 20
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'

display:
  - platform: ssd1306_i2c
    id: oled
    address: 0x3c
    model: "SH1106 128x64"
    pages:
      - id: custom
        lambda: |-
          it.printf(0, 0, id(open_sans_14), "%.1f°C", id(temp).state);
          it.printf(128, 0, id(open_sans_14), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
          it.line(0,17,128,17);
          it.printf(0,19, id(open_sans_9), "CO2");
          it.printf(0,27, id(open_sans_20), "%.0f", id(co2).state);
          it.printf(0,52, id(open_sans_9), "ppm");
          it.line(50,19,50,64);
          it.printf(54, 19, id(open_sans_9), "PM2.5");
          it.printf(54, 27, id(open_sans_20), "%.0f", id(pm_2_5).state);
          it.printf(54, 52, id(open_sans_9), "µg/m³");
          it.line(100,19,100,64);
          it.printf(104,18, id(open_sans_9), "TVOC");
          it.printf(104,29, id(open_sans_9), "%.0f", id(voc).state);
          it.printf(104,41, id(open_sans_9), "NOx");
          it.printf(104,52, id(open_sans_9), "%.0f", id(nox).state);

interval:
  - interval: 10s
    then:
      - display.page.show_next: oled
      - component.update: oled

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1

  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: Temperature
    humidity:
      id: humidity
      name: Relative Humidity
    address: 0x44
    update_interval: 10s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_1
    pm_1_0:
      id: pm_1_0
      name: "PM <1.0µm Concentration"
    pm_2_5:
      id: pm_2_5
      name: "PM <2.5µm Concentration"
    pm_10_0:
      id: pm_10_0
      name: "PM <10.0µm Concentration"
    pm_0_3um:
      id: pm_0_3um
      name: "PM >0.3µm Count"
      icon: mdi:blur
    pm_0_5um:
      id: pm_0_5um
      name: "PM >0.5µm Count"
      icon: mdi:blur
    pm_1_0um:
      id: pm_1_0um
      name: "PM >1.0µm Count"
      icon: mdi:blur
    pm_2_5um:
      id: pm_2_5um
      name: "PM >2.5µm Count"
      icon: mdi:blur
    update_interval: 3min
  - platform: senseair
    uart_id: uart_2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s
  - platform: sgp4x
    voc:
      id: voc
      name: "VOC Index"
      icon: mdi:chemical-weapon
      # See https://sensirion.com/media/documents/02232963/6294E043/Info_Note_VOC_Index.pdf
      # 0-150 green, 151-250 yellow, 251-400 orange, 401+ red
    nox:
      id: nox
      name: "NOx Index"
      icon: mdi:chemical-weapon
      # See https://sensirion.com/media/documents/9F289B95/6294DFFC/Info_Note_NOx_Index.pdf
      # 0-19 green, 20+ yellow (see PDF for why we don't do more than this)
    compensation:
      humidity_source: humidity
      temperature_source: temp

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: airgradient_wifi_signal
    update_interval: 60s

  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s
